### ISSUE TITLE
Better autocompletion

### ISSUE THREAD

**Issue by ddeboer** [driebit/mod_elasticsearch#12]
We now use a regular (match) query, which uses analyzed queries and terms. This is suboptimal for matching partial (prefix) strings. 

See http://rea.tech/implementing-autosuggest-in-elasticsearch/ for options.

**Comment by fredpook** [comment]
A Ginger general UI improvement with key up/down scrolling (https://github.com/driebit/ginger/issues/18) would be very nice too.

**Comment by ddeboer** [comment]
The [prefix](https://github.com/driebit/mod_elasticsearch#extra-query-arguments) search argument can now be used for this case.

Cf. https://github.com/driebit/ginger/pull/507
