### ISSUE TITLE
Searching for id:unique_name not supported

### ISSUE THREAD

**Issue by robvandenbogaard** [driebit/mod_elasticsearch#63]

**Comment by ddeboer** [comment]
It should be supported, but probably breaks on https://github.com/driebit/mod_elasticsearch/blob/3fc5e3fa2b2f491948a07b635b45bce7da4f9f06/support/elasticsearch_search.erl#L488. Do you want to fix this one, @robvandenbogaard?

**Comment by robvandenbogaard** [comment]
No error message, just no results. E.g. "home" should resolve to the numerical id of the home page, if that page has its unique name set to "home". I already had a fix lying around, adding a conversion from name to id.
